# Generated by Django 4.0.5 on 2022-07-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_body_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
